import Head from 'next/head'
import Header from '../components/Header'
import Image from 'next/image'
import Link from 'next/link'
import fs from 'fs/promises'
import styles from '../styles/Home.module.css'

export default function Home({ latestComics }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <main>
        <h2 className={styles.title}>Latest Comics</h2>
        {latestComics.map(comic => {
          return (
            <Link href={`./comic/${comic.id}`} key={comic.id}>
              <a>
                <Image
                  height={500}
                  width={500}
                  layout='intrinsic'
                  objectFit='contain'
                  src={comic.img}
                  alt={comic.alt}
                />
              </a>
            </Link>
          )
        })}
      </main>
    </div>
  )
}

export async function getStaticProps(context) {
  const files = await fs.readdir('./comics')
  const latestComicsFiles = files.slice(-8, files.length)

  const promisesReadFiles = latestComicsFiles.map(async file => {
    const content = await fs.readFile(`./comics/${file}`, 'utf-8')
    return JSON.parse(content)
  })

  const latestComics = await Promise.all(promisesReadFiles)

  return {
    props: {
      latestComics,
    },
  }
}
